### PR TITLE
Fix semantics of `isSameFile` in class file manager

### LINKED ISSUE #956: Unexpected error using a Java annotation processor
```
[E] [E-1] Errors during annotation processing
[E] [E18] XXXX.java:17
[E]       Exception during annotation processing: java.lang.IllegalArgumentException: Not supported: sbt.internal.inc.javac.WriteReportingJavaFileObject@3e42b4ef

// last error repeats many times, followed by errors about missing symbols

[E] [E12] YYYYYY.java:41
[E]       cannot find symbol
[E]         symbol:   class .....
[E]         location: class ....
```

### PR DESCRIPTION
**Pull request by pkolaczk**
Passing a WriteReportingFileObject to the original, wrapped
JavaFileManager may cause InvalidArgumentException. To avoid this,
we unwrap the original FileObject.

Fixes #956

### CODE REVIEW

File: backend/src/main/scala/bloop/CompilerCache.scala [hunk 1]
```diff
@@ -4,35 +4,22 @@ import java.io.File
...
-  FileObject,
-  ForwardingJavaFileManager,
-  StandardJavaFileManager,
-  ForwardingJavaFileObject,
-  JavaFileManager,
-  JavaFileObject,
-  JavaCompiler => JavaxCompiler
-}
-
+import javax.tools.{FileObject, ForwardingJavaFileManager, ForwardingJavaFileObject, JavaFileManager, JavaFileObject, StandardJavaFileManager, JavaCompiler => JavaxCompiler}
```
Comment (jvican) [inline backend/src/main/scala/bloop/CompilerCache.scala]: Can you leave the imports as they were and disable the formatter in intellij when hacking on bloop? You should be using the scalafmt formatter instead.

Comment (pkolaczk) [reply backend/src/main/scala/bloop/CompilerCache.scala]: The formatter touches only the modified lines. But, yeah, I'll try to set up scalafmt.
Thanks for heads up.

Comment (pkolaczk) [reply backend/src/main/scala/bloop/CompilerCache.scala]: How do I run `sbt scalafmt` on a single file? It reformats many other files if invoked on the whole project. :(

Comment (jvican) [reply backend/src/main/scala/bloop/CompilerCache.scala]: Try setting up scalafmt with IntelliJ. It has an option to reformat with save. Save only the file and it will be reformatted.

**Comment by pkolaczk** [comment]
Ok, formatted with `sbt scalafmt`

File: backend/src/main/scala/bloop/CompilerCache.scala [hunk 2]
```diff
@@ -295,6 +293,15 @@ final class CompilerCache(
           }
         }.asJava
       }
+
+      // Needed because JavaFileManager doesn't expect WriteReportingJavaFileObjects in isSameFile, fixes #956
+      override def isSameFile(a: FileObject, b: FileObject): Boolean = {
```
Comment (jvican) [inline backend/src/main/scala/bloop/CompilerCache.scala]: Can you add a test case?

Comment (pkolaczk) [reply backend/src/main/scala/bloop/CompilerCache.scala]: Ok, done

**Comment by pkolaczk** [comment]
Rebased
