### PR TITLE
Don't parse `--help` from Bloopgun

### LINKED ISSUE #1224: CLI --help flag doesn't work as advertised
```
 bloop --help                                                                          [I]
bloop 1.4.0-RC1-142-90456e06
Usage: bloop [options] [command] [command-options]


Available commands: about, autocomplete, bsp, clean, compile, configure, console, help, link, projects, run, test
Type `bloop 'command' --help` for help on an individual command
```

Bloop says to run `bloop 'command' --help`

As you can see from below I tried various incantations and none of them worked.

```
➜  palermo git:(master) ✗ bloop compile --help                                                                  [I]
Required project name not specified for 'compile'.
➜  palermo git:(master) ✗ bloop console --help                                                                  [I]
Required project name not specified for 'console'.
➜  palermo git:(master) ✗ bloop 'console' --help                                                                [I]
Required project name not specified for 'console’.
```

### PR DESCRIPTION
**Pull request by Duhemm**
Bloopgun was parsing the `--help` flag, and not passing it further to
`bloop.Cli`, which would therefore never display the help.

Fixes #1224

### CODE REVIEW

File: bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala [hunk 1]
```diff
@@ -587,14 +581,19 @@ class BloopgunCli(
     }
   }
 
+  private def helpRequested(cmd: String, cmdArgs: Array[String]): Boolean = {
+    def isHelp(str: String): Boolean = str == "-h" || str == "--help"
```
Comment (olafurpg) [inline bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala]: Does this handle `bloop help`? I think it's nice to be flexible and allow `bloop -h`, `bloop -help`, `bloop help` and `bloop --help`

Comment (Duhemm) [reply bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala]: Good point, I added `-help` and `help` as markers 👍
