### PR TITLE
fix: Only consider scala source files when lifting fatal errors

### LINKED ISSUE #2341: When fatal warnings set Java ones are also shown as errors
With this configuration:

```scala
val moduleB = project
  .in(file("moduleB"))
  .settings(
    scalaVersion := "3.3.3",
    scalacOptions ++= Seq(
      "-Xfatal-warnings"
    ),
    javacOptions ++= Seq(
      "-Xlint:unchecked"
    )
  )
```

and this file:

src/main/java/com/example/Service.java:
```java
package com.example;

import java.util.List;

public class Service {
	void create(List<Object> args) {
		var second = (java.util.Optional<String>) args.get(2);
		System.out.println(second);
	}
}
```

Bloop will show the cast warning as error.

### PR DESCRIPTION
**Pull request by masonedmison**
Closes #2341

### CODE REVIEW

File: frontend/src/test/scala/bloop/BaseCompileSpec.scala [hunk 1]
```diff
@@ -1163,6 +1163,64 @@ abstract class BaseCompileSpec extends bloop.testing.BaseSuite {
...
+      assertExitStatus(compiledState, ExitStatus.CompilationError)
+
+      val targetService = TestUtil.universalPath("a/src/Service.java")
+      assertNoDiff(
+        logger.renderErrors(exceptContaining = "Failed to compile"),
+        s"""[E1] ${targetService}:4
+           |     incompatible types: int cannot be converted to java.lang.String
+           |     L4: 123
+           |                          ^^^
+           |a/src/Service.java: L4 [E1], L6 [E2]
```
Comment (tgodzik) [inline frontend/src/test/scala/bloop/BaseCompileSpec.scala:1212]:
```suggestion
           |${TestUtil.universalPath("a/src/Service.java")}: L4 [E1], L6 [E2]
```
should help with the tests on Windows

**Review by tgodzik — CHANGES_REQUESTED** [review]

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks!
